SURGE_PROVIDER: "https://example.com/subscribe/<key>?protocols=smart&list=surge"
# CLASH_PROVIDER: "https://example.com/subscribe/<key>?protocols=smart&list=clash"

SURGE_OUTPUT: "/Users/<username>/Library/Mobile Documents/iCloud~com~nssurge~inc/Documents/profile-name.conf"
# CLASH_OUTPUT: "<path>/config.conf"
